# -*- coding: utf-8 -*-
"""MNIST_Digits_ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qDOPhZPSicgrDHrTyFD_yG0mTDsCP-pN
"""

import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Flatten , Input

(x_train,y_train),(x_test,y_test)=keras.datasets.mnist.load_data()

print(len(x_test))
print(len(x_train))

x_train[0].shape

x_train[0]

y_train

import matplotlib.pyplot as plt
plt.imshow(x_train[2])

x_train = x_train/255
x_test=x_test/255

x_train[0]

model = Sequential()
model.add(Input(shape=(28, 28)))
model.add(Flatten())
model.add(Dense(128,activation="relu"))
model.add(Dense(64,activation="relu"))
model.add(Dense(32,activation="relu"))
model.add(Dense(10,activation="softmax"))

model.summary()

model.compile(loss="sparse_categorical_crossentropy",optimizer="Adam",metrics=["accuracy"])

from tensorflow.keras.callbacks import EarlyStopping
early_stop = EarlyStopping(patience=10,monitor="val_loss",restore_best_weights=True)
history=model.fit(x_train,y_train,epochs=100,validation_split=0.2,callbacks=[early_stop])

y_prob =model.predict(x_test)

y_pred=y_prob.argmax(axis=1)

from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

import matplotlib.pyplot as plt
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

import matplotlib.pyplot as plt
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.imshow(x_test[0])

model.predict(x_test[0].reshape(1,28,28)).argmax(axis=1)

